import { readFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import { describe, expect, it } from "vitest"

// These lists are generated by tools/gen-wordlists.ts and committed. The engine
// treats them as a contract — word selection indexes into answers, guess
// validation is a lookup in allowed — so the invariants are worth pinning even
// though no code here produced them.

const WORDS = join(dirname(fileURLToPath(import.meta.url)), "..", "public", "words")
const read = (name: string) => readFileSync(join(WORDS, name), "utf8")
const parse = (name: string) => read(name).split("\n").filter(Boolean)

const answers = parse("answers.txt")
const allowed = parse("allowed.txt")

describe.each([
  ["answers", answers],
  ["allowed", allowed],
])("%s.txt", (name, words) => {
  it("contains only lowercase five-letter words", () => {
    expect(words.filter((w) => !/^[a-z]{5}$/.test(w))).toEqual([])
  })

  it("has no duplicates", () => {
    expect(words.length).toBe(new Set(words).size)
  })

  it("is sorted, so regenerating produces a readable diff", () => {
    expect(words).toEqual([...words].sort())
  })

  it("ends with a newline", () => {
    expect(read(`${name}.txt`).endsWith("\n")).toBe(true)
  })
})

describe("the two lists together", () => {
  it("keeps every answer guessable", () => {
    const guessable = new Set(allowed)
    expect(answers.filter((w) => !guessable.has(w))).toEqual([])
  })

  // Guarding the count, not just non-emptiness: a generator bug that silently
  // truncates the corpus would still satisfy every check above.
  it("is large enough to draw a run from", () => {
    expect(answers.length).toBe(2300)
    expect(allowed.length).toBeGreaterThan(10_000)
  })

  /*
   * Wordle bars plural answers, and the reason is mechanical rather than
   * literary: a plural answer makes the last slot a free S, which turns a
   * five-letter deduction into a four-letter one. In this game it would also
   * hand S a guaranteed position, which is a scoring problem as well as a
   * deduction one — every letter here can be bought an etching and a modifier.
   *
   * Guessing one stays legal. BANKS is a fine probe; it is just never the word.
   */
  it("never makes a plural the secret word", () => {
    const secret = new Set(answers)
    for (const word of ["zones", "banks", "cakes", "words", "girls", "boxes", "tries"]) {
      expect(secret.has(word), word).toBe(false)
      expect(allowed.includes(word), word).toBe(true)
    }
  })

  /*
   * The catch-all behind that spot check. The generator judges "plural" against
   * a hunspell lemma list this test cannot see, so it asserts the consequence
   * instead: a corpus of ordinary English is about a quarter plural by these
   * ranks, and 620 of these 2300 ended in S before the filter existed. What is
   * left is the words that merely happen to — GRASS, FOCUS, CHAOS.
   */
  it("keeps S off the end of almost every answer", () => {
    const sFinal = answers.filter((word) => word.endsWith("s"))
    expect(sFinal.length).toBeLessThan(answers.length / 20)
    expect(sFinal).toContain("grass")
  })
})
