import { readFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import { describe, expect, it } from "vitest"

// These lists are generated by tools/gen-wordlists.ts and committed. The engine
// treats them as a contract — word selection indexes into answers, guess
// validation is a lookup in allowed — so the invariants are worth pinning even
// though no code here produced them.

const WORDS = join(dirname(fileURLToPath(import.meta.url)), "..", "public", "words")
const read = (name: string) => readFileSync(join(WORDS, name), "utf8")
const parse = (name: string) => read(name).split("\n").filter(Boolean)

const answers = parse("answers.txt")
const allowed = parse("allowed.txt")

describe.each([
  ["answers", answers],
  ["allowed", allowed],
])("%s.txt", (name, words) => {
  it("contains only lowercase five-letter words", () => {
    expect(words.filter((w) => !/^[a-z]{5}$/.test(w))).toEqual([])
  })

  it("has no duplicates", () => {
    expect(words.length).toBe(new Set(words).size)
  })

  it("is sorted, so regenerating produces a readable diff", () => {
    expect(words).toEqual([...words].sort())
  })

  it("ends with a newline", () => {
    expect(read(`${name}.txt`).endsWith("\n")).toBe(true)
  })
})

describe("the two lists together", () => {
  it("keeps every answer guessable", () => {
    const guessable = new Set(allowed)
    expect(answers.filter((w) => !guessable.has(w))).toEqual([])
  })

  // Guarding the count, not just non-emptiness: a generator bug that silently
  // truncates the corpus would still satisfy every check above.
  it("is large enough to draw a run from", () => {
    expect(answers.length).toBe(2300)
    expect(allowed.length).toBeGreaterThan(10_000)
  })
})
